### PR TITLE
Add a custom recipe to annotate extractive Question Answering datasets

### PR DESCRIPTION
**Pull request by vitojph**
Custom recipe to use prodigy to create a dataset to train an extractive Question Answering system. As in SQuAD, each sample contains a `question`, a `context` (ie. a paragraph in natural language, related to the question and likely to contain a possible answer) and the specific `answer`, extracted directly from the context. Notice that the answer is a substring of the context.

See [this thread for the whole discussion](https://support.prodi.gy/t/annotating-an-extractive-qa-dataset-a-la-squad/2125).

### CODE REVIEW

**Comment by pjchungmd** [comment]
Hi @vitojph , very cool work! What is the expected format of the JSONL file for this recipe?

**Comment by sanchez-castro** [comment]
Same question as @pjchungmd :)
Also, what is the command to run this recipe?

**Comment by sanchez-castro** [comment]
I'm having this issue:
```✘ Invalid components returned by recipe 'qa'
config -> label   str type expected
{'view_id': 'ner_manual', 'dataset': 'test_qanda_extractive', 'stream': <generator object at 0x7fd1220d3508>, 'config': {'lang': 'en', 'label': ['answer_span'], 'labels': ['
answer_span']}}```

**Comment by koaning** [comment]
Closing due to radio silence.

**Pull request closed without merging**
