### PR TITLE
Link records across datasets with prodigy and dedupe.io

### PR DESCRIPTION
**Pull request by kabirkhan**
Adds a recipe for the python [dedupe](https://github.com/dedupeio/dedupe) library. 
I'm actively using a similar recipe at work for conflating taxonomies and have found this approach to be really fast and much nicer than dedupe's console labeler.

Bonus: It's also a nice example of using a custom HTML template interface.

I'm happy to work on more documentation and clean up the code a bit, just wanted to gauge interest before investing too much time.
Not sure if you want beyond basic recipes here or not.

### CODE REVIEW

**Comment by ines** [comment]
Yesssss, this is great! ✨ Thanks for submitting this. We were definitely hoping that this repo could also function as a place for users to share their own custom recipes (including ver specific solutions for different domains and integrations with other tools).

So I'd definitely love to merge this PR. I wonder how we can best group it into a category? (I'm worried that if we put everything into the root, the repo might soon get a bit messy.) Maybe we could have a top-level directory `community`, specifically for recipes contributed by others?

**Comment by kabirkhan** [comment]
Awesome! I'll clean this up a little, add a README.md and put it in a top-level directory called `contrib`. I'll follow up in a few days. Thanks for the support and awesome project!

**Comment by kabirkhan** [comment]
@ines added the `contrib` folder and docs

**Comment by ines** [comment]
Thanks so much! 🙏 Sorry for the delay – I kinda missed this after getting back from the holidays.

**Pull request merged**
